"""Add practice plan link to pitching outings

Revision ID: 238c373c3242
Revises: 3a1b9c8d7e6f
Create Date: 2025-09-04 16:51:32.856084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238c373c3242'
down_revision = '3a1b9c8d7e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitching_outings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'practice_plans', ['practice_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitching_outings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('practice_plan_id')

    # ### end Alembic commands ###
