"""Add practice plan details and fix structure

Revision ID: 02b06584d4db
Revises: 
Create Date: 2025-07-27 01:24:24.414074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b06584d4db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('registration_code', sa.String(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('display_coach_names', sa.Boolean(), nullable=False),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=False),
    sa.Column('pitching_rule_set', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaboration_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('game_notes', sa.Text(), nullable=True),
    sa.Column('associated_lineup_title', sa.String(), nullable=True),
    sa.Column('associated_rotation_date', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lineup_positions', sa.Text(), nullable=True),
    sa.Column('associated_game_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitching_outings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('pitcher', sa.String(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('pitches', sa.Integer(), nullable=True),
    sa.Column('innings', sa.Float(), nullable=True),
    sa.Column('pitcher_type', sa.String(), nullable=True),
    sa.Column('outing_type', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('position1', sa.String(), nullable=True),
    sa.Column('position2', sa.String(), nullable=True),
    sa.Column('position3', sa.String(), nullable=True),
    sa.Column('throws', sa.String(), nullable=True),
    sa.Column('bats', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pitcher_role', sa.String(), nullable=True),
    sa.Column('has_lessons', sa.String(), nullable=True),
    sa.Column('lesson_focus', sa.Text(), nullable=True),
    sa.Column('notes_author', sa.String(), nullable=True),
    sa.Column('notes_timestamp', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('emphasis', sa.Text(), nullable=True),
    sa.Column('warm_up', sa.Text(), nullable=True),
    sa.Column('infield_outfield', sa.Text(), nullable=True),
    sa.Column('hitting', sa.Text(), nullable=True),
    sa.Column('pitching_catching', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('innings', sa.Text(), nullable=True),
    sa.Column('associated_game_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scouted_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position1', sa.String(), nullable=True),
    sa.Column('position2', sa.String(), nullable=True),
    sa.Column('throws', sa.String(), nullable=True),
    sa.Column('bats', sa.String(), nullable=True),
    sa.Column('list_type', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('last_login', sa.String(), nullable=True),
    sa.Column('tab_order', sa.Text(), nullable=True),
    sa.Column('player_order', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('player_development_focuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_date', sa.String(), nullable=True),
    sa.Column('completed_date', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('last_edited_by', sa.String(), nullable=True),
    sa.Column('last_edited_date', sa.String(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_game_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_practice_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('practice_plan_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['practice_plan_id'], ['practice_plans.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('practice_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_plan_id'], ['practice_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_tasks')
    op.drop_table('player_practice_absences')
    op.drop_table('player_game_absences')
    op.drop_table('player_development_focuses')
    op.drop_table('users')
    op.drop_table('signs')
    op.drop_table('scouted_players')
    op.drop_table('rotations')
    op.drop_table('practice_plans')
    op.drop_table('players')
    op.drop_table('pitching_outings')
    op.drop_table('lineups')
    op.drop_table('games')
    op.drop_table('collaboration_notes')
    op.drop_table('teams')
    # ### end Alembic commands ###
