"""add practice_plan_link_to_pitching_log

Revision ID: 0b0102f59b0d
Revises: 3a1b9c8d7e6f
Create Date: 2025-09-04 21:59:12.096495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0102f59b0d'
down_revision = '3a1b9c8d7e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitching_outings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_pitching_outings_practice_plan_id_practice_plans", 'practice_plans', ['practice_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitching_outings', schema=None) as batch_op:
        batch_op.drop_constraint("fk_pitching_outings_practice_plan_id_practice_plans", type_='foreignkey')
        batch_op.drop_column('practice_plan_id')
    # ### end Alembic commands ###
