"""Initial database setup

Revision ID: 1a86625f588a
Revises:
Create Date: 2025-09-12 13:04:20.467373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a86625f588a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('registration_code', sa.String(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('display_coach_names', sa.Boolean(), nullable=False),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=False),
    sa.Column('pitching_rule_set', sa.String(), nullable=False),
    sa.Column('outfielder_count', sa.Integer(), nullable=False),
    sa.Column('default_practice_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('collaboration_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_collaboration_notes_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaboration_notes'))
    )
    op.create_table('opponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_opponents_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opponents'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('position1', sa.String(), nullable=True),
    sa.Column('position2', sa.String(), nullable=True),
    sa.Column('position3', sa.String(), nullable=True),
    sa.Column('throws', sa.String(), nullable=True),
    sa.Column('bats', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pitcher_role', sa.String(), nullable=True),
    sa.Column('has_lessons', sa.String(), nullable=True),
    sa.Column('lesson_focus', sa.Text(), nullable=True),
    sa.Column('notes_author', sa.String(), nullable=True),
    sa.Column('notes_timestamp', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('scouted_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position1', sa.String(), nullable=True),
    sa.Column('position2', sa.String(), nullable=True),
    sa.Column('throws', sa.String(), nullable=True),
    sa.Column('bats', sa.String(), nullable=True),
    sa.Column('list_type', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_scouted_players_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scouted_players'))
    )
    op.create_table('signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_signs_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signs'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('tab_order', sa.Text(), nullable=True),
    sa.Column('player_order', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_password_change_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token_version', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_users_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('game_notes', sa.Text(), nullable=True),
    sa.Column('associated_lineup_title', sa.String(), nullable=True),
    sa.Column('associated_rotation_date', sa.String(), nullable=True),
    sa.Column('our_score', sa.Integer(), nullable=True),
    sa.Column('opponent_score', sa.Integer(), nullable=True),
    sa.Column('post_game_summary', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], name=op.f('fk_games_opponent_id_opponents')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_games_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('player_development_focuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('progress_notes', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('last_edited_by', sa.String(), nullable=True),
    sa.Column('last_edited_date', sa.DateTime(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_development_focuses_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_development_focuses_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_development_focuses'))
    )
    op.create_table('game_quick_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_quick_notes_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_quick_notes'))
    )
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lineup_positions', sa.JSON(), nullable=True),
    sa.Column('associated_game_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['associated_game_id'], ['games.id'], name=op.f('fk_lineups_associated_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_lineups_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineups'))
    )
    op.create_table('player_game_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_player_game_absences_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_game_absences_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_game_absences_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_game_absences'))
    )
    op.create_table('practice_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('emphasis', sa.Text(), nullable=True),
    sa.Column('warm_up', sa.Text(), nullable=True),
    sa.Column('infield_outfield', sa.Text(), nullable=True),
    sa.Column('hitting', sa.Text(), nullable=True),
    sa.Column('pitching_catching', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source_game_id', sa.Integer(), nullable=True),
    sa.Column('source_game_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_game_id'], ['games.id'], name=op.f('fk_practice_plans_source_game_id_games'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_practice_plans_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_plans'))
    )
    op.create_table('rotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('innings', sa.JSON(), nullable=True),
    sa.Column('associated_game_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['associated_game_id'], ['games.id'], name=op.f('fk_rotations_associated_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_rotations_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rotations'))
    )
    op.create_table('pitching_outings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('pitches', sa.Integer(), nullable=True),
    sa.Column('innings', sa.Float(), nullable=True),
    sa.Column('pitcher_type', sa.String(), nullable=True),
    sa.Column('outing_type', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('practice_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_pitching_outings_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_pitching_outings_player_id_players')),
    sa.ForeignKeyConstraint(['practice_plan_id'], ['practice_plans.id'], name=op.f('fk_pitching_outings_practice_plan_id_practice_plans')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_pitching_outings_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pitching_outings'))
    )
    op.create_table('player_practice_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('practice_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_practice_absences_player_id_players')),
    sa.ForeignKeyConstraint(['practice_plan_id'], ['practice_plans.id'], name=op.f('fk_player_practice_absences_practice_plan_id_practice_plans')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_practice_absences_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_practice_absences'))
    )
    op.create_table('practice_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('practice_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_plan_id'], ['practice_plans.id'], name=op.f('fk_practice_tasks_practice_plan_id_practice_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_tasks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_tasks')
    op.drop_table('player_practice_absences')
    op.drop_table('pitching_outings')
    op.drop_table('rotations')
    op.drop_table('practice_plans')
    op.drop_table('player_game_absences')
    op.drop_table('lineups')
    op.drop_table('game_quick_notes')
    op.drop_table('player_development_focuses')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('signs')
    op.drop_table('scouted_players')
    op.drop_table('players')
    op.drop_table('opponents')
    op.drop_table('collaboration_notes')
    op.drop_table('teams')
    # ### end Alembic commands ###
