"""Add Timezone and Live Game State

Revision ID: 1c030d6d5134
Revises: 4a76228479d9
Create Date: 2026-08-12 00:32:22.153222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c030d6d5134'
down_revision = '4a76228479d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_live', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('live_current_inning', sa.String(), server_default='1', nullable=False))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(), server_default='America/Indiana/Indianapolis', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('live_current_inning')
        batch_op.drop_column('is_live')

    # ### end Alembic commands ###
