"""Add Game start_time and unique constraints for targets

Revision ID: 2141af5cf87f
Revises: 1c030d6d5134
Create Date: 2026-08-12 02:04:08.878245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2141af5cf87f'
down_revision = '1c030d6d5134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(), nullable=True))

    with op.batch_alter_table('player_pitch_targets', schema=None) as batch_op:
        batch_op.create_index('idx_unique_daily_target', ['team_id', 'player_id', 'local_date'], unique=True, sqlite_where=sa.text('game_id IS NULL'))
        batch_op.create_index('idx_unique_game_target', ['team_id', 'player_id', 'local_date', 'game_id'], unique=True, sqlite_where=sa.text('game_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_pitch_targets', schema=None) as batch_op:
        batch_op.drop_index('idx_unique_game_target', sqlite_where=sa.text('game_id IS NOT NULL'))
        batch_op.drop_index('idx_unique_daily_target', sqlite_where=sa.text('game_id IS NULL'))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
