"""Add default_practice_location to Team model

Revision ID: 2f2efca8e55a
Revises: b4c6b9609344
Create Date: 2025-09-03 20:18:24.790950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2efca8e55a'
down_revision = 'b4c6b9609344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_practice_location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('default_practice_location')

    # ### end Alembic commands ###
