"""Add post-game features and opponent tracking

Revision ID: 3a1b9c8d7e6f
Revises: 2f2efca8e55a
Create Date: 2025-09-04 12:25:00.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3a1b9c8d7e6f'
down_revision = '2f2efca8e55a'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)

    # Idempotent table creation for 'opponents'
    if 'opponents' not in inspector.get_table_names():
        op.create_table('opponents',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('team_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # Idempotent table creation for 'game_quick_notes'
    if 'game_quick_notes' not in inspector.get_table_names():
        op.create_table('game_quick_notes',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('text', sa.Text(), nullable=False),
            sa.Column('author', sa.String(), nullable=True),
            sa.Column('timestamp', sa.DateTime(), nullable=True),
            sa.Column('game_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # Idempotently add columns to 'games' table
    games_columns = [c['name'] for c in inspector.get_columns('games')]
    with op.batch_alter_table('games', schema=None) as batch_op:
        if 'our_score' not in games_columns:
            batch_op.add_column(sa.Column('our_score', sa.Integer(), nullable=True))
        if 'opponent_score' not in games_columns:
            batch_op.add_column(sa.Column('opponent_score', sa.Integer(), nullable=True))
        if 'post_game_summary' not in games_columns:
            batch_op.add_column(sa.Column('post_game_summary', sa.Text(), nullable=True))
        if 'opponent_id' not in games_columns:
            batch_op.add_column(sa.Column('opponent_id', sa.Integer(), nullable=True))

        # Check for foreign key before creating
        fks = inspector.get_foreign_keys('games')
        fk_exists = any(fk['name'] == 'fk_games_opponent_id_opponents' for fk in fks)
        if not fk_exists:
            batch_op.create_foreign_key('fk_games_opponent_id_opponents', 'opponents', ['opponent_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_opponent_id_opponents', type_='foreignkey')
        batch_op.drop_column('opponent_id')
        batch_op.drop_column('post_game_summary')
        batch_op.drop_column('opponent_score')
        batch_op.drop_column('our_score')

    op.drop_table('game_quick_notes')
    op.drop_table('opponents')
    # ### end Alembic commands ###
