"""Add GameRotationEvent, PlayerPitchTarget, and PitchingOuting.game_id

Revision ID: 4a76228479d9
Revises: 21ee544fa8a6
Create Date: 2026-08-11 20:39:17.275322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a76228479d9'
down_revision = '21ee544fa8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_rotation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('changed_by_user', sa.String(), nullable=True),
    sa.Column('before_alignment', sa.JSON(), nullable=True),
    sa.Column('after_alignment', sa.JSON(), nullable=True),
    sa.Column('old_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('new_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('reverted', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['new_pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['old_pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_pitch_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_pitches', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('pitching_outings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pitching_outings_game_id_games', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('pitching_outings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pitching_outings_game_id_games', type_='foreignkey')
        batch_op.drop_column('game_id')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_pitch_targets')
    op.drop_table('game_rotation_events')
    # ### end Alembic commands ###
