"""Add cascade delete to games

Revision ID: 991922418fd9
Revises: 61099c75ca7e
Create Date: 2025-09-27 15:17:08.249872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991922418fd9'
down_revision = '61099c75ca7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineups', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_lineups_games_associated_game_id', 'games', ['associated_game_id'], ['id'])

    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_rotations_games_associated_game_id', 'games', ['associated_game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rotations_games_associated_game_id', type_='foreignkey')

    with op.batch_alter_table('lineups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lineups_games_associated_game_id', type_='foreignkey')
    # ### end Alembic commands ###
