"""add game_id to pitching outing

Revision ID: a913a341d624
Revises: 61099c75ca7e
Create Date: 2025-08-29 17:23:47.122697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a913a341d624'
down_revision = '61099c75ca7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitching_outings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pitching_outings_game_id', 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitching_outings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pitching_outings_game_id', type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
