"""Add cascade delete from Game to Rotation

Revision ID: aa4102562d68
Revises: a913a341d624
Create Date: 2025-08-31 15:08:10.680913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4102562d68'
down_revision = 'a913a341d624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_rotations_associated_game_id_games', 'games', ['associated_game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rotations_associated_game_id_games', type_='foreignkey')

    # ### end Alembic commands ###
