"""Add location to PracticePlan

Revision ID: b4c6b9609344
Revises: aa4102562d68
Create Date: 2025-09-03 19:22:23.898648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c6b9609344'
down_revision = 'aa4102562d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_plans', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
